version: '3'
services:
    db:
        image: postgres:14.2
        container_name: $PROJECT_NAME-dev-db
        tty: true
        ports:
            - '${DB_PORT}:5432'
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_USER: $DB_USER
            POSTGRES_PASSWORD: $DB_PASSWORD
        volumes:
            - ./docker/data/dev/postgres:/var/lib/postgresql/data
