version: '3'
services:
    db:
        image: mysql:5.7
        container_name: base_project_mysql
        tty: true
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_USER: $DB_USER
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        volumes:
            - ./docker/data/mysql:/var/lib/mysql/

