version: '3.5'
services:
    db:
        extends:
            file: docker-compose-common.yml
            service: db

    backend:
        extends:
            file: docker-compose-common.yml
            service: backend

    http:
        image: steveltn/https-portal:1
        ports:
            - '80:80'
            - '443:443'
        restart: always
        environment:
            CLIENT_MAX_BODY_SIZE: "20M"
            ACCESS_LOG: default
            DOMAINS: $DOMAIN
            STAGE: 'staging' # Don't use production until staging works
            CUSTOM_NGINX_SERVER_CONFIG_BLOCK: |
                location /api/ {
                    proxy_pass http://backend:$BACKEND_PORT;
                }
        volumes:
            - ./docker/data/http:/var/lib/https-portal
            - ./docker/config/http/nginx-default.conf.erb:/var/lib/nginx-conf/default.conf.erb
            - ./packages/frontend/build/:/var/www/vhosts/$DOMAIN/
            - ./logs/http:/var/log/nginx/


