version: '3.5'
services:
    db:
        image: mysql:5.7
        tty: true
        environment:
            MYSQL_USER: $DB_USER
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        volumes:
            - ../data/mysql:/var/lib/mysql/

    backend:
        build:
            context: ../../packages/backend/
            dockerfile: Dockerfile
        env_file:
            - ../../packages/backend/.env

    http:
        image: nginx
        ports:
            - '8182:80'
        environment:
            API_URL: http://backend:$BACKEND_PORT
        volumes:
            - ./http/default.conf.template:/etc/nginx/templates/default.conf.template
            - ../../packages/frontend/build/:/var/www/

networks:
    default:
        name: e2e-network
