version: '3'
services:
    db:
        image: postgres:14.2
        container_name: $PROJECT_NAME-e2e-db
        tty: true
        ports:
            - '${DB_PORT}:5432'
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_USER: $DB_USER
            POSTGRES_PASSWORD: $DB_PASSWORD
        volumes:
            - ./docker/data/e2e/postgres:/var/lib/postgresql/data

    redis:
        image: redis:6.2
        container_name: $PROJECT_NAME-e2e-redis
        command: "redis-server --requirepass ${REDIS_PASSWORD}"
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - ./docker/redis:/var/lib/redis
        env_file: ../../.env
        environment:
            REDIS_PASSWORD: $REDIS_PASSWORD
