version: '3.5'
services:
    db:
        image: postgres:14.2
        container_name: $PROJECT_NAME-prod-db
        tty: true
        ports:
            - '${DB_PORT}:5432'
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_USER: $DB_USER
            POSTGRES_PASSWORD: $DB_PASSWORD
        volumes:
            - ./docker/data/prod/postgres:/var/lib/postgresql/data

    redis:
        image: redis:6.2
        container_name: $PROJECT_NAME-prod-redis
        command: "redis-server --requirepass ${REDIS_PASSWORD}"
        ports:
            - "${REDIS_PORT}:6379"
        environment:
            REDIS_PASSWORD: $REDIS_PASSWORD
        volumes:
            - ./docker/data/prod/redis:/var/lib/redis

    backend:
        build:
            context: ../../packages/backend/
            dockerfile: Dockerfile
        container_name: $PROJECT_NAME-prod-backend
        restart: always
        env_file:
            - ../../packages/backend/.env

    http:
        build:
            context: ../../packages/frontend/
            dockerfile: Dockerfile
        container_name: $PROJECT_NAME-prod-http
        ports:
            - '80:80'
        environment:
            API_URL: http://backend:$BACKEND_PORT
        volumes:
            - ../../logs/http:/var/log/nginx/
