version: '3.5'
services:
    db:
        image: postgres:14.2
        container_name: $PROJECT_NAME-e2e-db
        tty: true
        ports:
            - '${DB_PORT}:5432'
        environment:
            POSTGRES_DB: $DB_DATABASE
            POSTGRES_USER: $DB_USER
            POSTGRES_PASSWORD: $DB_PASSWORD
        volumes:
            - ./docker/data/e2e/postgres:/var/lib/postgresql/data

    redis:
        image: redis:6.2
        container_name: $PROJECT_NAME-e2e-redis
        command: "redis-server --requirepass ${REDIS_PASSWORD}"
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - ../data/e2e/redis:/var/lib/redis
        environment:
            REDIS_PASSWORD: $REDIS_PASSWORD

    backend:
        build:
            context: ../../packages/backend/
            dockerfile: Dockerfile
        container_name: $PROJECT_NAME-e2e-backend
        env_file:
            - ../../packages/backend/.env

    http:
        image: nginx
        container_name: $PROJECT_NAME-e2e-http
        ports:
            - '8182:80'
        environment:
            API_URL: http://backend:$BACKEND_PORT
        volumes:
            - ./http/default.conf.template:/etc/nginx/templates/default.conf.template
            - ../../packages/frontend/build/:/var/www/

networks:
    default:
        name: e2e-network
