version: '3.5'
services:
    db:
        image: mysql:5.7
        tty: true
        restart: always
        environment:
            MYSQL_USER: $DB_USER
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_PASSWORD: $DB_PASSWORD
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        volumes:
            - ../data/mysql:/var/lib/mysql/

    backend:
        build:
            context: ../../packages/backend/
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ../../packages/backend/.env
