version: '3.5'
services:
    db:
        extends:
            file: docker-compose-e2e.yml
            service: db

    backend:
        extends:
            file: docker-compose-e2e.yml
            service: backend

    http:
        extends:
            file: docker-compose-e2e.yml
            service: http

    e2e:
        build:
            context: ../../
            dockerfile: ./docker/config/e2e.Dockerfile
        environment:
            CYPRESS_BASE_URL: http://http
        volumes:
            - ../../test:/test
        depends_on:
            - http

