version: '3.5'
services:
    db:
        image: postgres:14.2
        tty: true
        restart: always
        environment:
            POSTGRES_DB: db_database
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_password
        volumes:
            - ./docker/data/prod/postgres:/var/lib/postgresql

    redis:
        image: redis:6.2
        command: "redis-server --requirepass redis_password --save 60 1 --maxmemory 8G"
        restart: always
        volumes:
            - ./docker/data/prod/redis:/data
        environment:
            REDIS_PASSWORD: redis_password

    backend:
        build:
            context: ../../packages/backend/
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ../../packages/backend/.env

    http:
        build:
            context: ../../packages/frontend/
            dockerfile: Dockerfile
        ports:
            - '80:80'
        environment:
            BACKEND_UPSTREAM: "server backend:3000;"
        volumes:
            - ../../logs/http:/var/log/nginx/
