import { Col, Divider, WithLoading } from "@peersyst/react-components";
import { LandingPageProps } from "module/landing/Landing.types";
import LandingPageArtistsSection from "../LandingPageArtistsSection/LandingPageArtistsSection";
import LandingPageHowWorkSection from "../LandingPageHowWorkSection/LandingPageHowWorkSection";
import LandingPageNftsSection from "../LandingPageNftsSection/LandingPageNftsSection";
import LandingPagePartnersSection from "../LandingPagePartnersSection/LandingPagePartnersSection";
import { useGetTrends } from "module/explore/query/useGetTrending";

function LandingPageContent({ ...rest }: WithLoading<LandingPageProps>): JSX.Element {
    const { data: { nfts, artists } = { nfts: [], artists: [] }, isLoading } = useGetTrends();
    // TODO : get How Work
    const items = [
        {
            image: "https://s3-alpha-sig.figma.com/img/e291/17c0/18ec079794dc535c91e5c04effbd56fd?Expires=1670198400&Signature=P-h-vlj3PMvizoeIy4d8b4KWnPqhuZ25eZqs~jkDz71abYogdS3RTD9lDSD9zl-tCscijLRsDtTyPT-XtFh4EU2HMclM2V~kAFOqHuVERP9T5fHvaSqxxvfkzSVam15kuw~FGPWc1my4uj5dT47xljrUdCtZCAcUyBekYOyTtPd2kUn8zDT4GUeHIQH7LQRvRVGVRUqGrZ65ihnC8vZqllzuAqMHskJSz3NvbDaK2oK2UCZe9blCn1hzAOiLC4k11J0s-fyEUH1peh8RC5eNgSxVzyEnhRz5Hho72D0CTwXiqFZRouBbl8~FTmmVx6oM4mEXK504B2UpdfMdN7czGw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA",
            title: "Create NFTs and manage your digital gallery",
            description:
                "Easily create your collections and NFTs without any XRPL programming knowledge. You can save your pieces as a draft at no cost and work on your collections until they're ready to go!",
        },
        {
            image: "https://s3-alpha-sig.figma.com/img/e291/17c0/18ec079794dc535c91e5c04effbd56fd?Expires=1670198400&Signature=P-h-vlj3PMvizoeIy4d8b4KWnPqhuZ25eZqs~jkDz71abYogdS3RTD9lDSD9zl-tCscijLRsDtTyPT-XtFh4EU2HMclM2V~kAFOqHuVERP9T5fHvaSqxxvfkzSVam15kuw~FGPWc1my4uj5dT47xljrUdCtZCAcUyBekYOyTtPd2kUn8zDT4GUeHIQH7LQRvRVGVRUqGrZ65ihnC8vZqllzuAqMHskJSz3NvbDaK2oK2UCZe9blCn1hzAOiLC4k11J0s-fyEUH1peh8RC5eNgSxVzyEnhRz5Hho72D0CTwXiqFZRouBbl8~FTmmVx6oM4mEXK504B2UpdfMdN7czGw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA",
            title: "Create NFTs and manage your digital gallery",
            description:
                "You can customize your themes, sections, and layouts with the visual builder to deliver the best experience to your collectors. Your own landing page for your own collections.",
        },
        {
            image: "https://s3-alpha-sig.figma.com/img/e291/17c0/18ec079794dc535c91e5c04effbd56fd?Expires=1670198400&Signature=P-h-vlj3PMvizoeIy4d8b4KWnPqhuZ25eZqs~jkDz71abYogdS3RTD9lDSD9zl-tCscijLRsDtTyPT-XtFh4EU2HMclM2V~kAFOqHuVERP9T5fHvaSqxxvfkzSVam15kuw~FGPWc1my4uj5dT47xljrUdCtZCAcUyBekYOyTtPd2kUn8zDT4GUeHIQH7LQRvRVGVRUqGrZ65ihnC8vZqllzuAqMHskJSz3NvbDaK2oK2UCZe9blCn1hzAOiLC4k11J0s-fyEUH1peh8RC5eNgSxVzyEnhRz5Hho72D0CTwXiqFZRouBbl8~FTmmVx6oM4mEXK504B2UpdfMdN7czGw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA",
            title: "Monitor the impact generated by your NFTs",
            description:
                "Once your drops are published or launched, you can easily monitor the impact your art generates every day. Find out how far you can go!",
        },
    ];

    return (
        <Col {...rest}>
            <Col gap={"5.5rem"}>
                <Divider />
                <LandingPageNftsSection nfts={nfts} loading={isLoading} />
                <LandingPageArtistsSection artists={artists} loading={isLoading} />
                <Col>
                    <Divider />
                    <LandingPageHowWorkSection items={items} />
                    <Divider />
                </Col>
                <LandingPagePartnersSection />
                <Divider />
            </Col>
        </Col>
    );
}

export default LandingPageContent;
