#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
    - ubuntu: [root, sys]
    - terraform

# Add users to the system. Users are added after groups are added.
users:
    - default
    - name: tf
      gecos: tf
      shell: /bin/bash
      primary_group: terraform
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: users, admin
      lock_passwd: false
      ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGzMrMCXTiti7fOhH5abcSzG29w7Eu2YaYD0clhpfN0KnLkF4wZNTLqytZyUnhjjP7tGYlgvsjmhZc9jaXPxSpi8PH4FKcHbFbUinbTR8PyAbJsgtJuLA4LQeO/MSo3YYGn3WW3WNC40It5dRFwxoTCp75LUXEtI9kVi0/ubLHBTLjl4c2bcobKdZjWAqrzPCUmgjNq84dN407KadeTt7jyvzDfIlEiaqu3zXlrpyDC/wbGg3oDpJvAtcdhsQg3QYQvtnS9djv75VIcKtOLv5D3+Akw0WRa04XDBmWySGBLC+CKK8eINPJTu/VihId3Jj1tnk7Z/Qe9YqCwu4fV8Qp adriacarrera@MacBook-Pro-de-Adria.local

# Clone repo and start hashicups backend
runcmd:
    - sudo su tf
    - cd /home/tf
    - sudo apt-get update
    - sudo apt-get -y -qq install docker.io docker-compose git
    - sudo docker login -u peersyst -p ${dockerReadToken}
    - sudo docker-compose up -d
    - sleep 30
    - sudo docker-compose exec -T backend node ./dist/src/database/seeders/index.js

write_files:
    - encoding: b64
      content: ${dockerComposeFile}
      path: /home/tf/docker-compose.yml
